# The primary workflow that handles building, testing, and deploying.

name: Main

on: [push, pull_request]

jobs:
  build-test:

    runs-on: ubuntu-20.04

    services:
      postgres:
        image: postgres:13.4-buster
        env:
          POSTGRES_USER: runner  # Github runner default.
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: psltest
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Needs to be deep enough to hit the last tagged version.

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Cache Maven
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Cache Pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Python Dependencies
        run: pip3 install -r psl-python/requirements.txt

      - name: Build with Maven
        run: mvn integration-test -B

      - name: Build Python Package
        run: python3 setup.py bdist_wheel
        working-directory: psl-python

      - name: Style and Lint
        run: ./.ci/style-and-lint.sh

      - name: Publish to test.pypi
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_PSLPYTHON }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: psl-pyton/dist
